global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Reactive.Linq;
global using NetDaemon.AppModel;
global using NetDaemon.HassModel;
global using AllenStreetNetDaemonApps.Utilities.NotificationUtilities;
global using HomeAssistantGenerated;
global using NetDaemon.Extensions.Scheduler;
global using Serilog;
global using System.Linq;
global using System.Threading.Tasks;
global using AllenStreetNetDaemonApps.Models;
global using AllenStreetNetDaemonApps.Utilities;
global using System.Text.Json;
global using System.Threading;
global using NetDaemon.HassModel.Entities;
global using ILogger = Serilog.ILogger;